### ISSUE TITLE
When to support 'find definition'?

### ISSUE THREAD

**Issue by dovahcrow** [emacs-pe/company-racer#4]

**Comment by marsam** [comment]
Hi, the scope of this package is only provide a company backend for racer. If you want 'find definition', you can use either:
- [racer](https://github.com/phildawes/racer/blob/master/editors/emacs/racer.el) (available in [melpa](http://melpa.org/#/racer)) which also provides a company backend.
- [racer.el](https://github.com/emacs-pe/racer.el) (not available in melpa)
