### ISSUE TITLE
No function signature provided

### ISSUE THREAD

**Issue by landaire** [emacs-pe/company-racer#5]
I'm not sure if this is an issue with company-racer or Spacemacs' `rust` layer (which uses company-racer) but I figured I'd ask here first: I have no function signatures shown in the completion tooltip, only the name and "completion type" (function, enum, etc.). Is there something special I need to do to enable this, or is that not provided by this package?

**Comment by matthew-piziak** [comment]
I have the same issue: http://emacs.stackexchange.com/questions/22435/display-documentation-in-company-results

**Comment by marsam** [comment]
Hi:
Sorry for the late response, I've added support for signatures.
Like the stackoverflow question mentioned, [emacs-racer](https://github.com/racer-rust/emacs-racer) now supports completion through `completion-at-point-functions` and `company-capf`, so installing both packages could be unnecessary, I've added a warning in the readme.
