### ISSUE TITLE
My autocomplete shows the whole path to the module/whatever - is it possible to turn this off?

### ISSUE THREAD

**Issue by hicksy994** [emacs-pe/company-racer#6]
When the autocomplete from company-racer kicks in, it shows the path where it is found for some reason. For example, if I start typing:

```
use std::i
```

it comes up with io /usr/src/rust/src/libstd/io/mod.rs : Module

Can i hide the path so it just suggests io?

**Comment by marsam** [comment]
Hi:
You can try the latest version and set `(setq company-racer-annotation-format "%m")` to only show `Module` as annotation.

**Comment by hicksy994** [comment]
Great, thanks.
